package:
    name: enginemeta
    version: 1.1.0
requirements:
    run:
        - psycopg2
        - ioos_qc_py2
        - requests ==2.13.0
        - concurrentloghandler ==0.9.1
        - pandas ==0.23.4
        - ion-functions ==2.4.5
        - numexpr ==2.6.2
        - netcdf4 ==1.4.2
        - nomkl
        - simplejson
        - python ==2.7.15
        - msgpack-python ==0.4.8
        - cachetools ==2.0.0
        - flask ==0.12
        - mi-instrument ==0.9.2
        - geoalchemy2 ==0.4.0
        - xarray ==0.9.2
        - ntplib ==0.3.3
        - gunicorn ==19.7.0
        - numpy ==1.16.0
        - scipy ==1.2.1
        - sqlalchemy ==1.1.5
        - ooi-data ==0.0.6
        - pygsw ==0.0.11
        - futures ==3.3.0
        - cassandra-driver ==3.9.0
about:
    summary: Ingest and stream engine metapackage
