{% set name = "ooi-data" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/oceanobservatories/ooi-data
  git_rev: v{{ version}}

requirements:
  build:
    - python <3
    - setuptools
    - numpy ==1.16
  run:
    - python <3
    - setuptools
    - numpy ==1.16
    - sqlalchemy >1,<2
    - geoalchemy2 <1

build:
  number: 1

test:
  imports:
    - ooi_data.postgres.model

about:
  home: http://oceanobservatories.org
  license: apache 2.0
  summary: Data model for the Ocean Observatories Project
