package:
    name: stream_engine
    version: 1.20.12

source:
    git_url: https://github.com/oceanobservatories/stream_engine
    git_rev: v1.20.12

requirements:
    run:

about:
    summary: Stream engine
