package:
    name: ingest_engine
    version: 1.4.5

source:
    git_url: git@ciw-gitlab.intra.oceanobservatories.org:engine/ingest_engine.git
    git_rev: v1.4.5

requirements:
    run:

about:
    summary: Ingest engine
