{% set name = "mi-instrument" %}
{% set version = "1.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/oceanobservatories/mi-instrument
  git_rev: v{{ version }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    # conda default channel
    - python
    - setuptools
    - pyzmq
    - pyyaml
    - numpy
    - nose
    - mock
    - sqlalchemy
    - psycopg2
    - gevent
    - ipython
    - docopt
    - requests
    - meld3
    - xarray
    - pandas

    # conda forge
    - librabbitmq ==1.6.1
    - kombu ==3.0.35
    - amqp ==1.4.9

    # conda ooi channel
    - ooi_port_agent
    - qpid-python ==0.32
    - python-consul ==0.6.0
    - apscheduler ==2.1.0
    - ntplib ==0.3.3
    - tqdm ==2.0.0

about:
  home: http://oceanobservatories.org
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: OOI Instrument Drivers
